#!/usr/bin/env bash
# Regenerates an app's icon set from the renderer in make_icon.py.
#
# Checked in as a script rather than as a one-off, because the icons are
# derived artefacts: when the mark changes, every size has to change with it,
# and doing that by hand is how an app ships with one stale size.
set -euo pipefail

cd "$(dirname "$0")/.."
APP="${1:-ledger}"
ROOT="apps/$APP"

if [[ ! -d "$ROOT" ]]; then
  echo "No such app: $APP" >&2
  exit 2
fi

# make_icon.py draws one mark, Ledger's. Running this for another app would
# quietly give that app Ledger's icon, which is the kind of mistake you only
# notice in a store listing.
if [[ "$APP" != "ledger" ]]; then
  echo "make_icon.py only draws Ledger's mark; $APP needs its own." >&2
  exit 2
fi

WORK="$(mktemp -d -t app-icons-XXXXXX)"
trap 'rm -rf "$WORK"' EXIT
MASTER="$WORK/master.png"
FOREGROUND="$WORK/foreground.png"
MONOCHROME="$WORK/monochrome.png"
python3 tool/make_icon.py "$MASTER" master >/dev/null
python3 tool/make_icon.py "$FOREGROUND" foreground >/dev/null
python3 tool/make_icon.py "$MONOCHROME" monochrome >/dev/null

# `-alpha off` matters for the 1024 marketing icon: App Store Connect rejects
# an icon with an alpha channel, and the rejection arrives after upload.
emit() { convert "$MASTER" -resize "${1}x${1}" -alpha off -strip "$2"; }

# The adaptive layers are the opposite case: they are composited by the
# launcher, so their transparency is the whole point.
emit_layer() {
  mkdir -p "$(dirname "$3")"
  convert "$1" -resize "${2}x${2}" -depth 8 -strip "$3"
}

IOS="$ROOT/ios/Runner/Assets.xcassets/AppIcon.appiconset"
emit 20   "$IOS/Icon-App-20x20@1x.png"
emit 40   "$IOS/Icon-App-20x20@2x.png"
emit 60   "$IOS/Icon-App-20x20@3x.png"
emit 29   "$IOS/Icon-App-29x29@1x.png"
emit 58   "$IOS/Icon-App-29x29@2x.png"
emit 87   "$IOS/Icon-App-29x29@3x.png"
emit 40   "$IOS/Icon-App-40x40@1x.png"
emit 80   "$IOS/Icon-App-40x40@2x.png"
emit 120  "$IOS/Icon-App-40x40@3x.png"
emit 120  "$IOS/Icon-App-60x60@2x.png"
emit 180  "$IOS/Icon-App-60x60@3x.png"
emit 76   "$IOS/Icon-App-76x76@1x.png"
emit 152  "$IOS/Icon-App-76x76@2x.png"
emit 167  "$IOS/Icon-App-83.5x83.5@2x.png"
emit 1024 "$IOS/Icon-App-1024x1024@1x.png"

RES="$ROOT/android/app/src/main/res"

# The flattened icon, for Android 7.0 and 7.1 - the two releases minSdk 24
# admits that came before adaptive icons.
emit 48  "$RES/mipmap-mdpi/ic_launcher.png"
emit 72  "$RES/mipmap-hdpi/ic_launcher.png"
emit 96  "$RES/mipmap-xhdpi/ic_launcher.png"
emit 144 "$RES/mipmap-xxhdpi/ic_launcher.png"
emit 192 "$RES/mipmap-xxxhdpi/ic_launcher.png"

# Android 8.0 and up mask an adaptive icon instead, and an app that offers
# only the flat one gets a shrunken square sat on a white backplate. The
# layers are a 108dp canvas rather than a 48dp one, so every density is
# larger here than above.
for density in "mdpi 108" "hdpi 162" "xhdpi 216" "xxhdpi 324" "xxxhdpi 432"; do
  set -- $density
  emit_layer "$FOREGROUND" "$2" "$RES/mipmap-$1/ic_launcher_foreground.png"
  emit_layer "$MONOCHROME" "$2" "$RES/mipmap-$1/ic_launcher_monochrome.png"
done

# The background half is a flat gradient. As a shape drawable it is exact at
# every density and weighs nothing, where five PNGs of it would be neither.
mkdir -p "$RES/drawable" "$RES/mipmap-anydpi-v26"
cat > "$RES/drawable/ic_launcher_background.xml" <<'XML'
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/make_app_icons.sh. The two colours are the ones
     tool/make_icon.py fills the master's gradient with. -->
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <gradient
        android:angle="270"
        android:startColor="#C46C31"
        android:endColor="#8C431E"
        android:type="linear" />
</shape>
XML

cat > "$RES/mipmap-anydpi-v26/ic_launcher.xml" <<'XML'
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/make_app_icons.sh.
     <monochrome> is read from Android 13 for themed icons and ignored by
     everything older, so it lives here rather than in a v33 variant that
     would have to repeat the other two layers. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
    <monochrome android:drawable="@mipmap/ic_launcher_monochrome" />
</adaptive-icon>
XML

# Both store listings want the icon on its own, outside the bundle, at
# different sizes and - annoyingly - in opposite formats. App Store Connect
# rejects an alpha channel; the Play Console asks for a 32-bit PNG, so this
# one keeps a channel that happens to be opaque everywhere.
mkdir -p "$ROOT/store"
emit 1024 "$ROOT/store/icon-1024.png"
convert "$MASTER" -resize 512x512 -alpha set -strip \
    PNG32:"$ROOT/store/icon-512.png"

echo "icons regenerated for $APP"
